### ISSUE TITLE
[tech] go-zero ecology

### ISSUE THREAD

**Issue by Alice52** [micro-services-roadmap/gz-core#3]
## go-zero(wip)

1. go-zero: [use zap](https://github.com/zeromicro/zero-contrib/blob/main/logx/zapx/readme.md)
    ```go
    type ZapWriter struct { logger *zap.Logger}
    
    func NewZapWriter(opts ...zap.Option) (logx.Writer, error) {
	    logger, _:= zap.NewProduction(opts...)
	    return &ZapWriter{ logger: logger}, nil
    }
    
    writer, _:= zapx.NewZapWriter()
    logx.SetWriter(writer)
    ```
2. go-zero: use gorm-gen
    - internal/source/gen: `gen.go + model/dal`
    - add dal to server-context
3. go-zero: api/rpc通信
    - rpc yaml
        ```yaml
        # 不向etcd注册rpc服务(什么都不写)
        --- 
        # 向etcd注册rpc服务
        Etcd:
          Hosts:
            - 127.0.0.1:2379
          Key: pms.rpc
        ```
    - api yaml
        ```yaml
        # api 直连 rpc 
        OrderRpcConf:
          Endpoints:
            - 127.0.0.1:2001
          NonBlock: true
        
        ---
        # etcd 服务发现
        PmsRpc:
          Etcd:
            Hosts:
              - localhost:2379
            Key: pms.rpc
          NonBlock: true
        ```
4. go-zero: viper + 加解密
    ```yaml
    # 核心就是向配置文件解析到 config.Config: viper 可以实现
    var configFile = flag.String("f", "etc/usercenter.yaml", "the config file")
    var c config.Config
    conf.MustLoad(*configFile, &c)
    ```
5. go-zero: [集成 swager](https://www.cnblogs.com/eatfishcat/p/17238521.html)
6. sql2pb: [生成 proto 文件](https://github.com/Mikaelemmmm/sql2pb)
7. goctl 自定义生成模板
8. go-zero: [stream 封装](https://github.com/kevwan/stream)
